// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class UnderwearForEveryone
    {
        public static class Armor
        {
            private static FormLink<IArmorGetter> Construct(uint id) => new FormLink<IArmorGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IArmorGetter> UFE_UnderwearBottom_1 => Construct(0x81e);
            public static FormLink<IArmorGetter> UFE_UnderwearBottom_0 => Construct(0x81f);
            public static FormLink<IArmorGetter> UFE_UnderwearTop => Construct(0x820);
            public static FormLink<IArmorGetter> UFE_UnderwearBottom => Construct(0x821);
            public static FormLink<IArmorGetter> UFE_UnderwearBottom_2 => Construct(0x823);
            public static FormLink<IArmorGetter> UFE_UnderwearBottom_3 => Construct(0x824);
            public static FormLink<IArmorGetter> UFE_UnderwearBottom_4 => Construct(0x825);
            public static FormLink<IArmorGetter> UFE_UnderwearBottom_5 => Construct(0x826);
            public static FormLink<IArmorGetter> UFE_UnderwearBottom_6 => Construct(0x827);
            public static FormLink<IArmorGetter> UFE_UnderwearBottom_7 => Construct(0x828);
            public static FormLink<IArmorGetter> UFE_UnderwearBottom_8 => Construct(0x829);
            public static FormLink<IArmorGetter> UFE_UnderwearTop_0 => Construct(0x833);
            public static FormLink<IArmorGetter> UFE_UnderwearTop_1 => Construct(0x834);
            public static FormLink<IArmorGetter> UFE_UnderwearTop_2 => Construct(0x835);
            public static FormLink<IArmorGetter> UFE_UnderwearTop_3 => Construct(0x836);
            public static FormLink<IArmorGetter> UFE_UnderwearTop_4 => Construct(0x837);
            public static FormLink<IArmorGetter> UFE_UnderwearTop_5 => Construct(0x838);
            public static FormLink<IArmorGetter> UFE_UnderwearTop_6 => Construct(0x839);
            public static FormLink<IArmorGetter> UFE_UnderwearTop_7 => Construct(0x83a);
            public static FormLink<IArmorGetter> UFE_UnderwearTop_8 => Construct(0x83b);
        }
    }
}
