// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class underwearforeveryone
    {
        public static class ArmorAddon
        {
            private static FormLink<IArmorAddonGetter> Construct(uint id) => new FormLink<IArmorAddonGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IArmorAddonGetter> UFE_UnderwearBottomAA_7 => Construct(0x808);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearBottomAA_8 => Construct(0x809);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearTopAA_0 => Construct(0x813);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearBottomAA => Construct(0x814);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearTopAA_1 => Construct(0x816);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearTopAA_2 => Construct(0x817);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearTopAA_3 => Construct(0x818);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearTopAA_4 => Construct(0x819);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearTopAA_5 => Construct(0x81a);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearTopAA_6 => Construct(0x81b);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearTopAA_7 => Construct(0x81c);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearTopAA_8 => Construct(0x81d);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearTopAA => Construct(0x83c);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearBottomAA_0 => Construct(0x801);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearBottomAA_1 => Construct(0x802);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearBottomAA_2 => Construct(0x803);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearBottomAA_3 => Construct(0x804);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearBottomAA_5 => Construct(0x806);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearBottomAA_4 => Construct(0x805);
            public static FormLink<IArmorAddonGetter> UFE_UnderwearBottomAA_6 => Construct(0x807);
        }
    }
}
