// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class UnderwearForEveryone
    {
        public static class MagicEffect
        {
            private static FormLink<IMagicEffectGetter> Construct(uint id) => new FormLink<IMagicEffectGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IMagicEffectGetter> UFE_ActorInventory_Effect => Construct(0x800);
            public static FormLink<IMagicEffectGetter> UFE_Actor_Effect => Construct(0x80c);
            public static FormLink<IMagicEffectGetter> UFE_Cloak_Effect => Construct(0xa01);
            public static FormLink<IMagicEffectGetter> UFE_Toggle_Effect => Construct(0xa04);
            public static FormLink<IMagicEffectGetter> UFE_Player_Tracker_Effect => Construct(0xa31);
        }
    }
}
