// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class underwearforeveryone
    {
        public static class Spell
        {
            private static FormLink<ISpellGetter> Construct(uint id) => new FormLink<ISpellGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ISpellGetter> UFE_ActorInventory_Spell => Construct(0x80a);
            public static FormLink<ISpellGetter> UFE_Actor_Spell => Construct(0x80d);
            public static FormLink<ISpellGetter> UFE_Cloak_Spell => Construct(0xa02);
            public static FormLink<ISpellGetter> UFE_Toggle_Spell => Construct(0xa03);
            public static FormLink<ISpellGetter> UFE_Player_Tracker_Spell => Construct(0xa32);
        }
    }
}
